M48
; DRILL file {KiCad 9.0.7} date 2026-05-06T21:18:28+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-06T21:18:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X60.32Y-15.575
X60.32Y-20.425
T2
X63.35Y-15.275
X63.35Y-20.725
T3
X3.5Y-3.5
X3.5Y-41.5
X61.5Y-3.5
X61.5Y-41.5
M30
